import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { Sliders, Activity, Info, X, Zap } from "lucide-react";

export default function ThreeReactorOverlay({ plant, onClose, onUpdatePlantMetrics }) {
  const mountRef = useRef(null);
  
  const props = plant?.properties || {};
  const plantName = props.plant_name || "Nuclear Facility";
  
  // App-linked simulation states
  const [controlRodDepth, setControlRodDepth] = useState(props.capacity_percentage || 90);
  const [selectedComponent, setSelectedComponent] = useState("rpv");
  const controlRodDepthRef = useRef(controlRodDepth);
  const selectedComponentRef = useRef(selectedComponent);

  // Multi-state component telemetry
  const telemetry = {
    rpv: {
      name: "Reactor Pressure Vessel (RPV)",
      temp: `${Math.round(290 + (controlRodDepth / 100) * 45)}°C`,
      pressure: `${Math.round(1950 + (controlRodDepth / 100) * 310)} PSI`,
      status: controlRodDepth > 10 ? "Supercritical" : "Subcritical (Cold Shutdown)",
      desc: "Houses the nuclear fuel assemblies (U-235). Water circulates under high pressure to absorb thermal energy generated by fission."
    },
    rods: {
      name: "Control Rod Drive System",
      temp: "145°C",
      pressure: "Ambient",
      status: controlRodDepth > 95 ? "Fully Withdrawn" : controlRodDepth < 5 ? "SCRAM / Fully Inserted" : "Regulating Fission",
      desc: "Controls the rate of fission by absorbing neutrons. Raising the rods increases reactor output; inserting them dims fission."
    },
    steam: {
      name: "Steam Generators (SG)",
      temp: `${Math.round(245 + (controlRodDepth / 100) * 35)}°C`,
      pressure: `${Math.round(850 + (controlRodDepth / 100) * 150)} PSI`,
      status: "Heat Exchanging",
      desc: "Transfers heat from the radioactive primary coolant loop to the non-radioactive secondary loop, producing high-pressure steam."
    },
    loop: {
      name: "Primary Coolant Loop",
      temp: `${Math.round(270 + (controlRodDepth / 100) * 30)}°C`,
      pressure: `${Math.round(1950 + (controlRodDepth / 100) * 310)} PSI`,
      status: "Flow Active",
      desc: "Circulates high-purity water through the core. Employs large primary coolant pumps to maintain pressure and prevent boiling."
    },
    dome: {
      name: "Containment Structure",
      temp: "32°C",
      pressure: "14.7 PSI",
      status: "Pressurized Shielding",
      desc: "A massive, steel-lined concrete dome designed to contain radiation and protect the reactor from extreme external impacts."
    }
  };

  useEffect(() => {
    controlRodDepthRef.current = controlRodDepth;
  }, [controlRodDepth]);

  useEffect(() => {
    selectedComponentRef.current = selectedComponent;
  }, [selectedComponent]);

  // Slider change handler - Syncs physical rod height in 3D and metrics back to the parent state
  const handleRodSliderChange = (e) => {
    const val = Number(e.target.value);
    setControlRodDepth(val);
    
    // Calculate new simulated MW output
    const capacity = Number(props.total_mw_capacity) || 1000;
    const newOutput = val > 10 ? (capacity * val) / 100 : 0;
    
    // Call the parent update callback to sync live dashboard metrics
    onUpdatePlantMetrics?.(props.id, val, newOutput);
  };

  useEffect(() => {
    if (!mountRef.current) return;

    // 1. Initialize Scene, Camera, WebGLRenderer
    const width = mountRef.current.clientWidth;
    const height = mountRef.current.clientHeight;
    
    const scene = new THREE.Scene();
    scene.background = null; // Transparent background to show the grid backdrop

    const camera = new THREE.PerspectiveCamera(40, width / height, 0.1, 100);
    
    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    renderer.setSize(width, height);
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.shadowMap.enabled = true;
    mountRef.current.appendChild(renderer.domElement);

    // 2. High-Tech Grid Floor
    const gridHelper = new THREE.GridHelper(20, 20, 0x00d4ff, 0x1f2937);
    gridHelper.position.y = 0;
    scene.add(gridHelper);

    // 3. Components Construction
    const objects = {};

    // Standard materials
    const metalMaterial = new THREE.MeshStandardMaterial({
      color: 0x4b5563,
      metalness: 0.85,
      roughness: 0.22,
      flatShading: false
    });
    
    const pipeMaterialRed = new THREE.MeshStandardMaterial({
      color: 0xef4444, // Primary Hot Leg
      metalness: 0.6,
      roughness: 0.3
    });

    const pipeMaterialBlue = new THREE.MeshStandardMaterial({
      color: 0x3b82f6, // Primary Cold Leg
      metalness: 0.6,
      roughness: 0.3
    });

    const glassMaterial = new THREE.MeshPhysicalMaterial({
      color: 0x00d4ff,
      transparent: true,
      opacity: 0.12,
      roughness: 0.1,
      metalness: 0.1,
      transmission: 0.6,
      thickness: 0.8,
      side: THREE.DoubleSide
    });

    // 3.1. Translucent Containment Dome
    const domeGeom = new THREE.CylinderGeometry(4.5, 4.5, 5, 32, 1, true); // Open ended cylinder
    const domeMesh = new THREE.Mesh(domeGeom, glassMaterial);
    domeMesh.position.y = 2.5;
    scene.add(domeMesh);
    objects.dome = domeMesh;

    // Dome Sphere Cap (cutaway semi-hemisphere)
    const capGeom = new THREE.SphereGeometry(4.5, 32, 16, 0, Math.PI * 2, 0, Math.PI / 2);
    const capMesh = new THREE.Mesh(capGeom, glassMaterial);
    capMesh.position.y = 5;
    scene.add(capMesh);

    // 3.2. Reactor Pressure Vessel (RPV)
    const rpvGroup = new THREE.Group();
    rpvGroup.position.y = 0;
    
    const rpvBodyGeom = new THREE.CylinderGeometry(1.2, 1.2, 3.2, 24);
    const rpvBodyMesh = new THREE.Mesh(rpvBodyGeom, metalMaterial);
    rpvBodyMesh.position.y = 1.6;
    rpvGroup.add(rpvBodyMesh);
    
    // RPV Cap
    const rpvCapGeom = new THREE.SphereGeometry(1.2, 24, 12, 0, Math.PI * 2, 0, Math.PI / 2);
    const rpvCapMesh = new THREE.Mesh(rpvCapGeom, metalMaterial);
    rpvCapMesh.position.y = 3.2;
    rpvGroup.add(rpvCapMesh);
    
    scene.add(rpvGroup);
    objects.rpv = rpvGroup;

    // 3.3. Glowing Cherenkov Core
    const coreGeom = new THREE.CylinderGeometry(0.85, 0.85, 1.4, 24);
    const coreMaterial = new THREE.MeshBasicMaterial({
      color: 0x00f0ff,
      transparent: true,
      opacity: 0.65
    });
    const coreMesh = new THREE.Mesh(coreGeom, coreMaterial);
    coreMesh.position.y = 1.1;
    rpvGroup.add(coreMesh);

    // 3.4. Control Rods Assembly
    const rodGroup = new THREE.Group();
    // Position rods above the core, will move down/up based on slider
    const rodAssemblyGeom = new THREE.CylinderGeometry(0.7, 0.7, 0.15, 16);
    const rodAssemblyMesh = new THREE.Mesh(rodAssemblyGeom, metalMaterial);
    rodAssemblyMesh.position.y = 0.8;
    rodGroup.add(rodAssemblyMesh);

    const individualRods = [];
    const rodMetal = new THREE.MeshStandardMaterial({ color: 0x1f2937, metalness: 0.9, roughness: 0.1 });
    
    for (let i = 0; i < 6; i++) {
      const angle = (i / 6) * Math.PI * 2;
      const x = Math.cos(angle) * 0.4;
      const z = Math.sin(angle) * 0.4;
      
      const rodGeom = new THREE.CylinderGeometry(0.06, 0.06, 1.4, 8);
      const rodMesh = new THREE.Mesh(rodGeom, rodMetal);
      rodMesh.position.set(x, 0, z);
      rodGroup.add(rodMesh);
      individualRods.push(rodMesh);
    }
    
    rodGroup.position.set(0, 3.4, 0); // starts suspended in the upper vessel
    scene.add(rodGroup);
    objects.rods = rodGroup;

    // 3.5. Steam Generators (SG)
    const sgGroup1 = new THREE.Group();
    sgGroup1.position.set(-2.6, 0, 0);
    const sgBodyGeom = new THREE.CylinderGeometry(0.75, 0.75, 3.8, 20);
    const sgMesh1 = new THREE.Mesh(sgBodyGeom, metalMaterial);
    sgMesh1.position.y = 1.9;
    sgGroup1.add(sgMesh1);
    const sgCapGeom = new THREE.SphereGeometry(0.75, 20, 10, 0, Math.PI * 2, 0, Math.PI / 2);
    const sgCapMesh1 = new THREE.Mesh(sgCapGeom, metalMaterial);
    sgCapMesh1.position.y = 3.8;
    sgGroup1.add(sgCapMesh1);
    scene.add(sgGroup1);

    const sgGroup2 = sgGroup1.clone();
    sgGroup2.position.set(2.6, 0, 0);
    scene.add(sgGroup2);
    objects.steam = [sgGroup1, sgGroup2];

    // 3.6. Primary Coolant Loop Pipes
    const pipeGroup = new THREE.Group();
    // Hot Leg (RPV to SG) - Red (Left)
    const hotLeftGeom = new THREE.CylinderGeometry(0.2, 0.2, 1.4, 16);
    const hotLeftMesh = new THREE.Mesh(hotLeftGeom, pipeMaterialRed);
    hotLeftMesh.rotation.z = Math.PI / 2;
    hotLeftMesh.position.set(-1.9, 2.0, 0);
    pipeGroup.add(hotLeftMesh);

    // Hot Leg (Right)
    const hotRightMesh = hotLeftMesh.clone();
    hotRightMesh.position.set(1.9, 2.0, 0);
    pipeGroup.add(hotRightMesh);

    // Cold Leg (SG to RPV) - Blue (Left)
    const coldLeftGeom = new THREE.CylinderGeometry(0.2, 0.2, 1.4, 16);
    const coldLeftMesh = new THREE.Mesh(coldLeftGeom, pipeMaterialBlue);
    coldLeftMesh.rotation.z = Math.PI / 2;
    coldLeftMesh.position.set(-1.9, 0.8, 0);
    pipeGroup.add(coldLeftMesh);

    // Cold Leg (Right)
    const coldRightMesh = coldLeftMesh.clone();
    coldRightMesh.position.set(1.9, 0.8, 0);
    pipeGroup.add(coldRightMesh);

    scene.add(pipeGroup);
    objects.loop = pipeGroup;

    // 3.7. Glowing Flow Particles (Circulating through pipes)
    const particles = [];
    const particleGeom = new THREE.SphereGeometry(0.09, 8, 8);
    const hotParticleMat = new THREE.MeshBasicMaterial({ color: 0xff3b4e });
    const coldParticleMat = new THREE.MeshBasicMaterial({ color: 0x00d4ff });

    // Left hot path (-1.2 to -2.6 at height 2.0)
    for (let i = 0; i < 4; i++) {
      const p = new THREE.Mesh(particleGeom, hotParticleMat);
      p.userData = { type: "hot", dir: -1, startX: -1.2, endX: -2.6, y: 2.0, progress: i / 4 };
      p.position.set(p.userData.startX, 2.0, 0);
      scene.add(p);
      particles.push(p);
    }
    // Right hot path (1.2 to 2.6 at height 2.0)
    for (let i = 0; i < 4; i++) {
      const p = new THREE.Mesh(particleGeom, hotParticleMat);
      p.userData = { type: "hot", dir: 1, startX: 1.2, endX: 2.6, y: 2.0, progress: i / 4 };
      p.position.set(p.userData.startX, 2.0, 0);
      scene.add(p);
      particles.push(p);
    }
    // Left cold path (-2.6 to -1.2 at height 0.8)
    for (let i = 0; i < 4; i++) {
      const p = new THREE.Mesh(particleGeom, coldParticleMat);
      p.userData = { type: "cold", dir: 1, startX: -2.6, endX: -1.2, y: 0.8, progress: i / 4 };
      p.position.set(p.userData.startX, 0.8, 0);
      scene.add(p);
      particles.push(p);
    }
    // Right cold path (2.6 to 1.2 at height 0.8)
    for (let i = 0; i < 4; i++) {
      const p = new THREE.Mesh(particleGeom, coldParticleMat);
      p.userData = { type: "cold", dir: -1, startX: 2.6, endX: 1.2, y: 0.8, progress: i / 4 };
      p.position.set(p.userData.startX, 0.8, 0);
      scene.add(p);
      particles.push(p);
    }

    // 4. Lights
    const ambientLight = new THREE.AmbientLight(0xffffff, 0.26);
    scene.add(ambientLight);

    const dirLight = new THREE.DirectionalLight(0xffffff, 1.2);
    dirLight.position.set(5, 10, 7);
    dirLight.castShadow = true;
    scene.add(dirLight);

    // Glowing core point light for Cherenkov glow
    const coreLight = new THREE.PointLight(0x00f0ff, 4.0, 10);
    coreLight.position.set(0, 1.2, 0);
    scene.add(coreLight);

    // 5. Camera Initial Positioning and Custom Orbit Controls
    let cameraRot = { theta: 0.4, phi: Math.PI / 3 };
    let cameraRadius = 13.5;
    
    const updateCameraPosition = () => {
      camera.position.x = cameraRadius * Math.sin(cameraRot.phi) * Math.sin(cameraRot.theta);
      camera.position.y = cameraRadius * Math.cos(cameraRot.phi);
      camera.position.z = cameraRadius * Math.sin(cameraRot.phi) * Math.cos(cameraRot.theta);
      camera.lookAt(0, 1.8, 0);
    };
    updateCameraPosition();

    // Custom mouse/touch event listeners for orbiting
    let isDragging = false;
    let prevMousePos = { x: 0, y: 0 };
    const canvasDom = renderer.domElement;

    const handleMouseDown = (e) => {
      isDragging = true;
      prevMousePos = { x: e.clientX, y: e.clientY };
    };

    const handleMouseMove = (e) => {
      if (!isDragging) return;
      const deltaX = e.clientX - prevMousePos.x;
      const deltaY = e.clientY - prevMousePos.y;
      prevMousePos = { x: e.clientX, y: e.clientY };

      cameraRot.theta -= deltaX * 0.0065;
      cameraRot.phi = Math.max(0.08, Math.min(Math.PI / 2 - 0.05, cameraRot.phi - deltaY * 0.0065));
      updateCameraPosition();
    };

    const handleMouseUp = () => {
      isDragging = false;
    };

    const handleWheel = (e) => {
      e.preventDefault();
      cameraRadius = Math.max(7.5, Math.min(22, cameraRadius + e.deltaY * 0.0095));
      updateCameraPosition();
    };

    canvasDom.addEventListener("mousedown", handleMouseDown);
    window.addEventListener("mousemove", handleMouseMove);
    window.addEventListener("mouseup", handleMouseUp);
    canvasDom.addEventListener("wheel", handleWheel, { passive: false });

    // Touch support for mobile devices
    const handleTouchStart = (e) => {
      if (e.touches.length === 1) {
        isDragging = true;
        prevMousePos = { x: e.touches[0].clientX, y: e.touches[0].clientY };
      }
    };
    const handleTouchMove = (e) => {
      if (!isDragging || e.touches.length !== 1) return;
      const deltaX = e.touches[0].clientX - prevMousePos.x;
      const deltaY = e.touches[0].clientY - prevMousePos.y;
      prevMousePos = { x: e.touches[0].clientX, y: e.touches[0].clientY };

      cameraRot.theta -= deltaX * 0.0085;
      cameraRot.phi = Math.max(0.08, Math.min(Math.PI / 2 - 0.05, cameraRot.phi - deltaY * 0.0085));
      updateCameraPosition();
    };
    canvasDom.addEventListener("touchstart", handleTouchStart, { passive: true });
    canvasDom.addEventListener("touchmove", handleTouchMove, { passive: true });
    canvasDom.addEventListener("touchend", handleMouseUp);

    // 7. Component Selection Highlights
    const highlightTarget = () => {
      // Return standard colors
      glassMaterial.color.setHex(0x00d4ff);
      glassMaterial.opacity = 0.12;
      metalMaterial.color.setHex(0x4b5563);
      pipeMaterialRed.color.setHex(0xef4444);
      pipeMaterialBlue.color.setHex(0x3b82f6);

      // Highlight selected structure in wireframe/emissive glow
      const activeComponent = selectedComponentRef.current;
      if (activeComponent === "dome") {
        glassMaterial.color.setHex(0x00ff8c); // emerald highlight
        glassMaterial.opacity = 0.3;
      } else if (activeComponent === "rpv") {
        metalMaterial.color.setHex(0x60a5fa); // glowing blue
      } else if (activeComponent === "rods") {
        // Glowing rods
      } else if (activeComponent === "loop") {
        pipeMaterialRed.color.setHex(0xfc8181);
        pipeMaterialBlue.color.setHex(0x93c5fd);
      }
    };

    // 8. Animation Loop
    let animationId;
    let clock = new THREE.Clock();

    const animate = () => {
      animationId = requestAnimationFrame(animate);
      const delta = clock.getDelta();
      const elapsed = clock.getElapsedTime();
      const currentRodDepth = controlRodDepthRef.current;

      // 8.1. Move particles inside pipes
      // speed scales with control rod depth (thermal activity)
      const flowSpeed = 0.3 + (currentRodDepth / 100) * 0.85;

      particles.forEach((p) => {
        const ud = p.userData;
        ud.progress += delta * flowSpeed;
        if (ud.progress > 1) ud.progress = 0;

        const distance = ud.endX - ud.startX;
        const currentX = ud.startX + distance * ud.progress;
        
        p.position.x = currentX;
        
        // Add a tiny sinusoidal wobble to the particle to make it feel fluid and flowing
        p.position.y = ud.y + Math.sin(elapsed * 5.0 + ud.progress * 10) * 0.04;
      });

      // 8.2. Animate Cherenkov radiation core pulse
      const activeCoreIntensity = currentRodDepth / 100;
      if (activeCoreIntensity > 0.05) {
        coreMaterial.color.setHex(0x00f0ff);
        coreMaterial.opacity = 0.35 + Math.sin(elapsed * 4.5) * 0.15 * activeCoreIntensity;
        coreLight.intensity = (2.2 + Math.sin(elapsed * 6.0) * 0.6) * activeCoreIntensity;
      } else {
        // Core is subcritical, cold shutdown (dark charcoal/faint decay heat glow)
        coreMaterial.color.setHex(0xff3b3b); // red decay heat glow
        coreMaterial.opacity = 0.12;
        coreLight.intensity = 0.1;
      }

      // 8.3. Animate control rods position based on state
      // rodGroup position y scales: 3.4 (withdrawn, 100% capacity) down to 2.1 (inserted, 0% capacity)
      const targetY = 2.1 + (currentRodDepth / 100) * 1.3;
      // Smooth interpolation for nice physical responsiveness
      rodGroup.position.y = THREE.MathUtils.lerp(rodGroup.position.y, targetY, 0.12);

      // Rotate RPV core slightly just for high-tech micro-movement
      rpvGroup.rotation.y = elapsed * 0.08;
      highlightTarget();

      renderer.render(scene, camera);
    };
    animate();

    // 9. Handle Resize
    const handleResize = () => {
      if (!mountRef.current) return;
      const w = mountRef.current.clientWidth;
      const h = mountRef.current.clientHeight;
      camera.aspect = w / h;
      camera.updateProjectionMatrix();
      renderer.setSize(w, h);
    };
    window.addEventListener("resize", handleResize);

    return () => {
      cancelAnimationFrame(animationId);
      window.removeEventListener("resize", handleResize);
      canvasDom.removeEventListener("mousedown", handleMouseDown);
      window.removeEventListener("mousemove", handleMouseMove);
      window.removeEventListener("mouseup", handleMouseUp);
      canvasDom.removeEventListener("wheel", handleWheel);
      canvasDom.removeEventListener("touchstart", handleTouchStart);
      canvasDom.removeEventListener("touchmove", handleTouchMove);
      canvasDom.removeEventListener("touchend", handleMouseUp);
      if (mountRef.current && renderer.domElement) {
        mountRef.current.removeChild(renderer.domElement);
      }
      scene.clear();
    };
  }, []);

  const activeTelemetry = telemetry[selectedComponent];

  return (
    <div className="three-reactor-overlay">
      <div className="three-reactor-card">
        {/* Header */}
        <div className="three-reactor-header">
          <div className="title-block">
            <Zap className="accent-glow spin-on-hover" size={18} style={{ color: "#00d4ff" }} />
            <div>
              <h3>3D Core Inspector</h3>
              <span>{plantName}</span>
            </div>
          </div>
          <button className="icon-button close-btn" onClick={onClose} aria-label="Exit 3D View">
            <X size={16} />
          </button>
        </div>

        {/* Viewport & HUD split */}
        <div className="three-reactor-body">
          {/* WebGL Canvas Holder */}
          <div ref={mountRef} className="three-webgl-mount">
            <div className="instructions-badge">
              <Info size={11} style={{ marginRight: 4 }} />
              <span>Drag to rotate • Scroll to zoom</span>
            </div>
          </div>

          {/* Holographic Diagnostic HUD */}
          <div className="three-hud-panel">
            <div className="hud-header">
              <Activity size={14} style={{ color: "#00d4ff" }} />
              <h4>Telemetry HUD</h4>
            </div>

            {/* Component Selector */}
            <div className="component-selector">
              <span className="hud-eyebrow">Select System</span>
              <div className="selector-grid">
                <button className={selectedComponent === "rpv" ? "active" : ""} onClick={() => setSelectedComponent("rpv")}>RPV Core</button>
                <button className={selectedComponent === "rods" ? "active" : ""} onClick={() => setSelectedComponent("rods")}>Control Rods</button>
                <button className={selectedComponent === "steam" ? "active" : ""} onClick={() => setSelectedComponent("steam")}>Steam Gen</button>
                <button className={selectedComponent === "loop" ? "active" : ""} onClick={() => setSelectedComponent("loop")}>Coolant Loop</button>
                <button className={selectedComponent === "dome" ? "active" : ""} onClick={() => setSelectedComponent("dome")}>Dome</button>
              </div>
            </div>

            <div className="hud-divider" />

            {/* Telemetry readout */}
            <div className="telemetry-readout">
              <h5 className="telemetry-title">{activeTelemetry.name}</h5>
              <div className="readout-grid">
                <div className="readout-card">
                  <span>Operating Temp</span>
                  <strong style={{ color: selectedComponent === "rods" ? "#e2e8f0" : "#ff3b4e" }}>{activeTelemetry.temp}</strong>
                </div>
                <div className="readout-card">
                  <span>Loop Pressure</span>
                  <strong style={{ color: "#00d4ff" }}>{activeTelemetry.pressure}</strong>
                </div>
              </div>
              <div className="telemetry-status">
                <span className="telemetry-status-dot" style={{ background: activeTelemetry.status.includes("Shutdown") ? "#ef4444" : "#4ade80" }} />
                <span>{activeTelemetry.status}</span>
              </div>
              <p className="telemetry-desc">{activeTelemetry.desc}</p>
            </div>
          </div>
        </div>

        {/* Reactor Control Deck Slider */}
        <div className="three-control-deck">
          <div className="control-label-row">
            <div className="deck-title-block">
              <Sliders size={14} style={{ color: "#ff8c00" }} />
              <h4>Core Regulation Deck</h4>
            </div>
            <div className="metric-badge">
              <span>Simulated Output:</span>
              <strong className="num">
                {controlRodDepth > 10 
                  ? `${Math.round((Number(props.total_mw_capacity) || 1000) * (controlRodDepth / 100))} MW` 
                  : "0 MW (Shutdown)"}
              </strong>
              <span className="metric-pct num">({controlRodDepth}%)</span>
            </div>
          </div>
          <div className="control-slider-wrapper">
            <span className="slider-limit-label low">0% SCRAM</span>
            <input
              type="range"
              min={0}
              max={100}
              step={1}
              value={controlRodDepth}
              onChange={handleRodSliderChange}
              className="reactor-power-slider"
            />
            <span className="slider-limit-label high">100% MAX</span>
          </div>
        </div>
      </div>
    </div>
  );
}
